"""Add unique constraint to session_keys

Revision ID: c35295a018f7
Revises: d131994f0c8c
Create Date: 2025-01-31 14:59:33.934607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35295a018f7'
down_revision: Union[str, None] = 'd131994f0c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_key_uc', 'session_keys', type_='unique')
    op.create_unique_constraint('_user_key_local_session_id_uc', 'session_keys', ['user_id', 'key', 'local_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_key_local_session_id_uc', 'session_keys', type_='unique')
    op.create_unique_constraint('_user_key_uc', 'session_keys', ['user_id', 'key'])
    # ### end Alembic commands ###
