[build]
builder = "nixpacks"
buildCommand = """
# Install Node.js and npm
curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
apt-get install -y nodejs

# Build frontend
cd ui
npm install
npm run build
cd ..

# Install Python dependencies
pip install -r requirements.txt

# Ensure build directory exists and copy files
mkdir -p ui/build
cp -r ui/.svelte-kit/output/client/* ui/build/
"""

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30 